### ISSUE TITLE
ArgumentError: uncaught throw :breakout_nav

### ISSUE THREAD

**Issue by Intrepidd** [deivid-rodriguez/pry-byebug#2]
Hi,

first of all thanks for this gem.

I'm having an issue, I'm debugging a spec, and I call pry with the usual ``binding.pry`` at some point.

I get this error when I try to run ``next`` or ``step`` for the first time, then it jumps to the next call of ``binding.pry`` and step / next works properly :

    ArgumentError: uncaught throw :breakout_nav
    from /Users/Intrepidd/.gem/ruby/2.0.0/gems/pry-byebug-1.0.1/lib/pry-byebug/commands.rb:209:in `throw'

Any Idea on how to fix this ? 

Thanks

**Comment by deivid-rodriguez** [comment]
@aledalgrande @mjrk What's the reason to use `pry.binding` instead of `binding.pry`?

**Comment by aledalgrande** [comment]
simply remembering things wrong :ambulance:

**Comment by deivid-rodriguez** [comment]
@aledalgrande Could you try to reproduce this against last master? I seem to be getting

    Cannot find local context. Did you use `binding.pry`?

which seems like a better error message.

**Comment by deivid-rodriguez** [comment]
Closing for lack of feedback.
