### ISSUE TITLE
byebug 11 compatibility

### ISSUE THREAD

**Issue by aried3r** [deivid-rodriguez/pry-byebug#208]
I saw that the last time the version was bumped support for older versions was dropped.

https://github.com/deivid-rodriguez/pry-byebug/commit/7f5b57e1f5bf2505146d516e603762a955ee16a1

Is this the way to go for byebug 11 compatibility or should we do something like `'>= 10', '< 12'` or be even more optimistic and do `~> 10`?

**Comment by aried3r** [comment]
Ah, just saw your byebug_11 branch. https://github.com/deivid-rodriguez/pry-byebug/tree/byebug_11

Then I'll close this :)

**Comment by 23tux** [comment]
The branch no longer exists, can you say something when support for byebug 11 will be released?

**Comment by aried3r** [comment]
I think soon after https://github.com/deivid-rodriguez/pry-byebug/pull/213 is merged.

**Comment by deivid-rodriguez** [comment]
Yeah! :)
