### ISSUE TITLE
Fix pry dependency requirement

### ISSUE THREAD

**Issue by esambo** [deivid-rodriguez/pry-byebug#300]
In order to resolve to a functioning version combination of pry that doesn't raise error `NameError: uninitialized constant Pry::Command::ExitAll`
As a developer having to use Ruby 2.2.0
I want a new pry-byebug 3.6.x version to resolve to pry `<0.13`

**Comment by BigAndini** [comment]
I encounter this same error with pry-byebug 3.7.0, pry 0.13.1 and ruby 2.3.3.

**Comment by andersonreinkordt** [comment]
Also with `ruby 2.7.1`, `pry-byebug 3.7.0`, `pry 0.13.1`

**Comment by deivid-rodriguez** [comment]
I think we fixed this in recent versions, let me know if that's not the case!
