### ISSUE TITLE
remove n / s / c aliases

### ISSUE THREAD

**Issue by banister** [deivid-rodriguez/pry-byebug#34]
Please. These short-cuts are great for a pure debugger, but pry has to be a REPL as well and those single letters are very, very common scratch variables. I get a lot of confused messages from people burnt by these short-cuts.

Putting the code for defining the aliases in the README (like `pry-debugger` does) is a decent compromise, IMO :)

thanks!

**Comment by grk** [comment]
Any chance for a released version that fixes this?

**Comment by deivid-rodriguez** [comment]
I'll try to release a new version in the next three months. In the meantime just use master!

**Comment by chaimk** [comment]
OMG. Thank god I found this thread. I was using c as a variable and getting the obscure error for no apparent reason. Horrific... Thanks for changing it, and the sooner the better!

**Comment by mbigras** [comment]
For folks hitting this issue via google. You can get the shortcuts back by adding the following to your `~/.pryrc` file:

```
if defined?(PryByebug)
  Pry.commands.alias_command 'c', 'continue'
  Pry.commands.alias_command 's', 'step'
  Pry.commands.alias_command 'n', 'next'
  Pry.commands.alias_command 'f', 'finish'
end
```

Taken from the [README](https://github.com/deivid-rodriguez/pry-byebug#matching-byebug-behaviour)
