### ISSUE TITLE
Please consider reverting 49de00cf89c

### ISSUE THREAD

**Issue by rf-** [deivid-rodriguez/pry-byebug#35]
This is the ["Now `pry` starts at first line after `binding.pry`"](https://github.com/deivid-rodriguez/pry-byebug/commit/49de00cf89cab30a633efd20a22622a81a10a08b) commit. It's not that this behavior is worse per se, but it violates the expectations of anyone who's already a Pry user and makes it feel like there's an off-by-one bug somewhere. I think `pry-byebug` probably shouldn't modify the experience of using Pry unless the user specifically opts into it by using one of the debugging commands.

**Comment by alesguzik** [comment]
Could you make it configurable at least? This feature may be useful for those who use debugging features often, but there are lots of people who use pry just to eval code in a context. In our case one developer in a team needed debugging features, added pry-byebug to Gemfile, and now everyone else suffer from this behaviour. Thank you.

**Comment by deivid-rodriguez** [comment]
Read the linked issue, that's the current state of things.
