### ISSUE TITLE
Pry Byebug specifies an older version of Pry

### ISSUE THREAD

**Issue by quintrino** [deivid-rodriguez/pry-byebug#350]
https://github.com/deivid-rodriguez/pry-byebug/blob/34ba6766d998d934169cd5e4887da2b69a884cde/pry-byebug.gemspec#L25

Looks like the Gemspec requires 0.13, but Pry has now released 0.14

Is it possible to update this to allow both 0.13 and 0.14?

**Comment by jorge-precich** [comment]
I think there's a dependabot pr for this, noticed the same issue when running `bundle outdated`. #346
