### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by justin808** [deivid-rodriguez/pry-byebug#363]
The latest versions of pry-byebug 3.9.0 and pry 0.13 seem to cause issues with setting breakpoints.

I documented the issue here.

https://forum.shakacode.com/t/fixing-error-from-setting-a-pry-breakpoint/2101

Using the master branch here and the latest release pry gem fix the issue.

**Comment by bastelfreak** [comment]
Hi,
would it be possible to get a new release? The latest one blocks pry 0.14.x :(

**Comment by quintrino** [comment]
I believe that @deivid-rodriguez is hoping to find a solution for https://github.com/deivid-rodriguez/pry-byebug/issues/343 before pushing up a new release.

**Comment by deivid-rodriguez** [comment]
I pushed a solution and released it as 3.10.0, let me know how it goes, thanks!
