### ISSUE TITLE
Relax restriction for byebug version

### ISSUE THREAD

**Issue by matheussilvasantos** [deivid-rodriguez/pry-byebug#377]
Any chance to make `pry-byebug` work with `byebug` 11.1?

**Comment by deivid-rodriguez** [comment]
Pry-byebug should support byebug 11.1, which problem are you having?

**Comment by matheussilvasantos** [comment]
I tried to install `ruby_jard` without removing `pry-byebug`. But `bundler` can't install `byebug` 11.1, needed for `ruby_yard`, because `pry-byebug` needs `~> 11.0`.

**Comment by deivid-rodriguez** [comment]
The `~> 11.0` requirement is perfectly compatible with `11.1`, it must be something else that was preventing `byebug` from being installed.

**Comment by matheussilvasantos** [comment]
Indeed, it is. 🤦 
Sorry for that. I've updated `byebug`, and it worked.

**Comment by deivid-rodriguez** [comment]
No problem!
