### ISSUE TITLE
The version 3.10.0 breaks rails console

### ISSUE THREAD

**Issue by AliSepehri** [deivid-rodriguez/pry-byebug#391]
After upgrading my `pry-byebug` to the version `3.10.0`, my `rails console` has been broken:

<img width="1378" alt="Screenshot 2022-08-16 at 16 46 05" src="https://user-images.githubusercontent.com/7887290/184909263-52b1118b-d7c9-4943-b329-694653b5fb01.png">

**Comment by deivid-rodriguez** [comment]
Hi, that's too bad, sorry. Which version of pry are you using? Is this reproducible on a plain Rails app?

**Comment by silasb** [comment]
We are also noticing this with 3.10.0

**Comment by deivid-rodriguez** [comment]
Are you using pry 0.13?

**Comment by silasb** [comment]
No, we are using pry 0.14.1

**Comment by silasb** [comment]
We are also using `pry-rails (0.3.9)` as well.

**Comment by deivid-rodriguez** [comment]
Yes, I figured that since otherwise your Rails console wouldn't use pry, right? However, I get this issue with pry-bye bug 3.9.0 as well, so it might be an older regression? Or maybe you upgraded pry and pry-byebug at the same time?

**Comment by AliSepehri** [comment]
No, for me it only happens with the version `3.10.0`. I checked the latest changes and I just create a PR that fixes my issue.

**Comment by deivid-rodriguez** [comment]
This is super weird.
