### ISSUE TITLE
Confusing behavior of breaks command

### ISSUE THREAD

**Issue by everm1nd** [deivid-rodriguez/pry-byebug#47]
byebug have a commands break and breaks. With break you can delete breakpoint doing this:

break --delete N

After deletion it types list of all remaining breakpoints. But when you type breaks --delete N it does not respect --delete flag and show no error messages. Just typing the same output - list of all available breakpoints. For my it was a little bit confusing. Maybe it's better to throw error or implement --delete flag support for breaks.

**Comment by deivid-rodriguez** [comment]
Hi again, @everm1nd ! :smile: 

If you want to give this a try, this should be an easy one to fix. This is the file where that stuff happens: https://github.com/deivid-rodriguez/pry-byebug/blob/master/lib/pry/commands/breakpoint.rb

**Comment by everm1nd** [comment]
@deivid-rodriguez Ok. I'll see what I can do here

**Comment by deivid-rodriguez** [comment]
:+1: Great

**Comment by deivid-rodriguez** [comment]
@everm1nd Did you ever get to this?

**Comment by deivid-rodriguez** [comment]
@everm1nd This should be fixed in last master. I completely dropped the `breaks` command. The correct (and only) way to list breakpoints now is `break` without arguments.

**Comment by everm1nd** [comment]
@deivid-rodriguez :+1:
