### ISSUE TITLE
Feature to set alias for `binding.pry`

### ISSUE THREAD

**Issue by Liooo** [deivid-rodriguez/pry-byebug#54]
I'm a bit uncomfortable with having to type `binding.pry` every time.
There's a gem [kentaroi/pry-alias](https://github.com/kentaroi/pry-alias) for making an alias for `binding.pry`.
Isn't it a nice idea to embed this feature in pry-byebug? Giving an option to set whatever alias name in .pryrc or something/

**Comment by deivid-rodriguez** [comment]
So `pry-alias` does not currently work with `pry-byebug`?

**Comment by Liooo** [comment]
It does quite well.
But the point is I thought it's a good idea to make this feature embedded in pry-byebug.
It probably is just a few lines of changes, and also users won't want to put 'pry-alias' just for this feature in their Gemfile.

**Comment by deivid-rodriguez** [comment]
I think most users won't be interested in this feature and most of the ones who want something like this, would just configure an snippet in their editor (for example, [using UltiSnips for vim](https://github.com/honza/vim-snippets/blob/master/snippets/ruby.snippets#L620-621)).

In any case, if this was to be included by default somewhere, it should be `pry` itself, which is the gem providing `binding.pry`.

Cheers!

**Comment by Liooo** [comment]
Okay sorry that was my mistake, I'll try to ask guys of pry anyway!
Thanks!

**Comment by deivid-rodriguez** [comment]
No problem @Liooo
