### ISSUE TITLE
Feature Request: Allow 'continue' to accept a line number argument

### ISSUE THREAD

**Issue by fetchak** [deivid-rodriguez/pry-byebug#56]
It'd be great if pry-byebug's "continue" worked [like byebug's](https://gist.github.com/fetchak/a8e963aab48779441c82), accepting a line number as argument.

Thanks for your work on this gem.

**Comment by deivid-rodriguez** [comment]
PR's welcome.

**Comment by deivid-rodriguez** [comment]
@fetchak This should be fixed in last master. Could you confirm?

**Comment by fetchak** [comment]
Confirmed. Thanks

**Comment by deivid-rodriguez** [comment]
:+1:
