### ISSUE TITLE
Test with byebug 5.0

### ISSUE THREAD

**Issue by rhymes** [deivid-rodriguez/pry-byebug#62]
pry-byebug is bound to byebug ~> 4.0, there's a new byebug 5.0.0

**Comment by deivid-rodriguez** [comment]
I know, what do you want me to do?

Before bumping the dependency, we should verify it works fine, no? Do you want to do it?

**Comment by rhymes** [comment]
Ah ah sorry, I've been quite cryptic, I just wanted to tell you about the new release but then I realized you are the author of byebug too and I felt dumb :-)

**Comment by krainboltgreene** [comment]
What are the breaking API changes in 5.0 from 4.0?

**Comment by deivid-rodriguez** [comment]
I think none of them should affect `pry-byebug`, but someone has to verify it.

**Comment by Quintasan** [comment]
This probably doesn't count as a formal test but today I've been playing around with byebug 5.0.0 in a new Rails application and ran pry from there. I didn't manage to break anything within an hour of normal debugging session.

**Comment by deivid-rodriguez** [comment]
I've just released a new version that depends on `byebug 5`.
