### ISSUE TITLE
break does not list breakpoints

### ISSUE THREAD

**Issue by antmg83** [deivid-rodriguez/pry-byebug#65]
I'm using version 3.1.0 and adding breakpoints by line number:-
```
break 14 # => output shown to say that break point has been enabled
break #=> no output shown
```
When running `break --disable-all` it displays the previous assigned breakpoint as being disabled

**Comment by deivid-rodriguez** [comment]
I just noticed this and cannot be reproduce in `3.2.0`. Please reopen if I'm missing something.
