### ISSUE TITLE
Re-execute command

### ISSUE THREAD

**Issue by stugol** [deivid-rodriguez/pry-byebug#66]
I really need the ability to re-run a previous line of code during debugging. For example, suppose an exception occurs and a rescue block runs pry. To determine the cause of the exception, I need to jump back up and run the failing line again. But there is no way to do this. We need either a "goto line" command, or a "retry failing code" command.

Any chance of this, please?

**Comment by deivid-rodriguez** [comment]
This is quite tricky and won't be implemented in a long time (if ever). This is the feature request in `byebug`: deivid-rodriguez/byebug#60

**Comment by deivid-rodriguez** [comment]
I also recently found out about this pry plugin that might fit your needs: https://github.com/awwaiid/pry-timetravel

**Comment by stugol** [comment]
Thanks. But that doesn't really help, as I would have to invoke ```snap``` before the exception actually occurred, which would require prescience.

**Comment by deivid-rodriguez** [comment]
Welcome, good luck!
