### ISSUE TITLE
Unable to quite from code inspect mode

### ISSUE THREAD

**Issue by JikkuJose** [deivid-rodriguez/pry-byebug#68]
I placed `binding.pry` inside a pretty long loop and after inspecting two rounds tried to quit with: `quit`/`q!`/`exit`/`Ctrl-C`/`Ctrl-D` but there was no use! Help!

**Comment by deivid-rodriguez** [comment]
Try to reproduce this using only `pry`. If it still happens, report the issue there, otherwise reopen this issue.

If you reopen this issue, please make sure you read https://github.com/deivid-rodriguez/pry-byebug/blob/master/CONTRIBUTING.md first and follow the instructions there.
