### ISSUE TITLE
Gemspec has special characters

### ISSUE THREAD

**Issue by MoMenne** [deivid-rodriguez/pry-byebug#70]
Hi,

This might be an error with my configuration or the character set that I am using.

I'm having difficulty adding the pry-byebug gem to my Gemfile.
`gem "pry-byebug", github: 'deivid-rodriguez/pry-byebug'`

There error message was as follows: 
`There was a SyntaxError while loading pry-byebug.gemspec: 
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/pry-byebug-b9353e64ff09/pry-byebug.gemspec:6: invalid multibyte char (US-ASCII)
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/pry-byebug-b9353e64ff09/pry-byebug.gemspec:6: invalid multibyte char (US-ASCII)
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/pry-byebug-b9353e64ff09/pry-byebug.gemspec:6: syntax error, unexpected end-of-input, expecting ']'
  gem.authors = ['David Rodríguez', 'Gopal Patel']`

Please let me know if this is something that should be fixed and sorry in advance if I have the wrong character set  :-)

Thanks for your gem!  It's awesome.

**Comment by deivid-rodriguez** [comment]
@MoMenne Does the latest commit in master fix your problem?

**Comment by deivid-rodriguez** [comment]
@MoMenne Any feedback?

**Comment by MoMenne** [comment]
Perfect.  Thanks for changing that.
