### ISSUE TITLE
Next goes into Pry-remote Gem

### ISSUE THREAD

**Issue by YOUConsulting** [deivid-rodriguez/pry-byebug#78]
Hi!

I'm trying to get Pry Remote running with Pry-Byebug! Now since the upgrade to Rails 4.x.x and Ruby 2.x.x I can still get into Pry-remote but when I type next strange behaviour happens! 

For details please check my stackoverflow topic edit 2: 

http://stackoverflow.com/questions/32780971/pry-remote-not-triggered-rails-4/32818381?noredirect=1#comment53499372_32818381

**Comment by deivid-rodriguez** [comment]
Closing in favor of #33
