### ISSUE TITLE
Segmentation Fault ```ARObject.valid?```

### ISSUE THREAD

**Issue by daino3** [deivid-rodriguez/pry-byebug#79]
I'm not sure where to start looking for crash logs when it comes to this, but here is what I'm using and an output of my pry-shell. Can you point me in the direction of what else you need to reproduce this? 

using:
- Yosemite 10.10.3
- ruby 2.2.2
- rspec 3.3.2
- mysql 0.3.18
- pry-byebug 3.2.0
- pry 0.10.2

```
[1] pry(#<FirmsController>)> @firm
=> #<Firm:0x000000043c3828
 id: 2,
 firm_id: "executing-firm-id-1",
 email: nil,
 created_at: Tue, 06 Oct 2015 15:34:55 UTC +00:00,
 updated_at: Tue, 06 Oct 2015 15:34:55 UTC +00:00>

[2] pry(#<FirmsController>)> Firm.count
=> 1

[3] pry(#<FirmsController>)> @firm.valid?
Segmentation fault
[vagrant@localhost vagrant]$
```

**Comment by deivid-rodriguez** [comment]
@daino3 The only SEGVs I've seen around `byebug` in ages are related to https://github.com/deivid-rodriguez/byebug/pull/160. Can you still reproduce this?

**Comment by daino3** [comment]
@deivid-rodriguez - No, I nuked my VM / reprovisioned and it seemed to have fixed itself. Sorry - I should have closed this issue. Thanks for following up!

**Comment by deivid-rodriguez** [comment]
No problem, sorry for taking this long to reply!
