### ISSUE TITLE
commands, aliased or not, overshadow variables

### ISSUE THREAD

**Issue by adrianomitre** [deivid-rodriguez/pry-byebug#83]
After adding the suggested alias_command to my .pryrc, trying to set any single character aliased command with a space after it, such as in the following
`s = 1`
generates the following error
> Error: Cannot find local context. Did you use `binding.pry`?

which is the same error one would get with
    `s`
which means that Pry is parsing `s = nil` as command `s` with arguments `= 1`, which is obviously not intended. Removing spaces in the assignment, i.e., `s=1` seems to work, but the the value is only accessible via `binding.local_variable_get(:s)`, which is far from convenient.

Maybe this is a Pry parsing limitation, but a workaround is very much desired. At least a warning in the Matching Byebug Behaviour section the README.md is in order.

This issue is a sibling of https://github.com/pry/pry/issues/1490.

**Comment by deivid-rodriguez** [comment]
After a quick read of the linked issue, this should be closed too, right?

**Comment by adrianomitre** [comment]
Right
