### ISSUE TITLE
Can you save the byebug session options in a pry-byebug session?

### ISSUE THREAD

**Issue by pdbradley** [deivid-rodriguez/pry-byebug#85]
Couldn't seem to do it within the pry-byebug session.  Is it disabled?

![image](https://cloud.githubusercontent.com/assets/448399/13090314/f0586f46-d4c2-11e5-9d28-142acd91ff77.png)

**Comment by deivid-rodriguez** [comment]
Sorry, I somehow had unfollowed this repo, so I haven't been getting notifications for new issues. :sweat: 

`save` is not available. `pry-byebug` is a `pry` REPL with some additions and changes from `byebug`. I guess the best option would be to check for similar functionality inside `pry`.
