### ISSUE TITLE
User defined "step"

### ISSUE THREAD

**Issue by fgarcia** [deivid-rodriguez/pry-byebug#86]
Is it possible to redefine, just a little bit, how step works?

Take this code as an example:

```ruby
require 'pry'
require 'forwardable'

module Bar
  def self.run
    puts 'run'
  end
end

module Foo
  extend SingleForwardable
  @ctx = ::Bar
  def_delegators :@ctx, :run
end

binding.pry
Foo.run
```

There are cases when I delegate method calls with the **forwardable** lib, or with **method_missing** and I would like a way to customize **step** so it ignores some files. In the example above I would like **step** to ignore the ruby library file `forwardable.rb` and **step** again when finding that library.

Even if it looks like a potentially problematic feature, I always define an environment variable to override hacks like that.

**Comment by deivid-rodriguez** [comment]
I think you want `step 2`.

**Comment by fgarcia** [comment]
I know I can do "step 2"

What I want is to not be forced to remember for each function of my own library if I must step 2, 3, 4... times to avoid the library code I want to ignore.

I forked the library but I could not find a clean way to automatically repeat "step" depending on the current frame

**Comment by deivid-rodriguez** [comment]
I see, you want something like this, right? https://github.com/deivid-rodriguez/byebug/issues/47

**Comment by fgarcia** [comment]
yep!
so it is already in the C library but not exposed?

I've just realized I could try writing a custom Pry macro like `my_step` but it would be way nicer and more idiomatic just using `step`

**Comment by deivid-rodriguez** [comment]
Nope, it's just an open issue...
