### ISSUE TITLE
after install disabled C-c in tmux

### ISSUE THREAD

**Issue by ChrisCPO** [deivid-rodriguez/pry-byebug#93]
After installing this gem in my Gemspec, it has disabled my tmux C-c (clear/exit command) instead of exit/clear as expected it does nothing, in order to leave the debugger I need to type exit. Any thoughts?

I'm positive this gem was on my system before but not this on project till I installed it. I have not used it with tmux before as I recently switched to tmux.

pry-byebug 3.3.0

**Comment by deivid-rodriguez** [comment]
Hi @ChrisCPO , could you review your report? I think it has some grammatical issues and I'm having trouble to understand.

**Comment by ChrisCPO** [comment]
@deivid-rodriguez  opps sorry fixed.

**Comment by deivid-rodriguez** [comment]
@ChrisCPO Does this happen when using `pry` alone?

**Comment by ChrisCPO** [comment]
@deivid-rodriguez yes it is.

**Comment by deivid-rodriguez** [comment]
Ok, so you should report this to the pry project. Regards.

**Comment by ChrisCPO** [comment]
@deivid-rodriguez  yep sorry to bother you.

**Comment by deivid-rodriguez** [comment]
No problem!
